//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratorio.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de calibración.
        /// </summary>
        public static string CalibrationDate {
            get {
                return ResourceManager.GetString("CalibrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string DeleteImageAlt {
            get {
                return ResourceManager.GetString("DeleteImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desasignar.
        /// </summary>
        public static string DownArrowImageAlt {
            get {
                return ResourceManager.GetString("DownArrowImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al remover el instrumento de la maquina..
        /// </summary>
        public static string ErrorDelMachineTool {
            get {
                return ResourceManager.GetString("ErrorDelMachineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el instrumento. Se puede deber a que el instrumento está asociado a una máquina..
        /// </summary>
        public static string ErrorDelTool {
            get {
                return ResourceManager.GetString("ErrorDelTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el tipo de instrumento. Se puede deber a que existen instrumentos asociados a este tipo..
        /// </summary>
        public static string ErrorDelToolType {
            get {
                return ResourceManager.GetString("ErrorDelToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al asignar herramienta a la maquina. Se puede deber a que ya existe un instrumento del mismo tipo asociado..
        /// </summary>
        public static string ErrorInsMachineTool {
            get {
                return ResourceManager.GetString("ErrorInsMachineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al insertar el instrumento. Se puede deber a que el código proporcionado ya existe..
        /// </summary>
        public static string ErrorInsTool {
            get {
                return ResourceManager.GetString("ErrorInsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al insertar tipo de instrumento. Se puede deber a que el nombre proporcionado ya existe..
        /// </summary>
        public static string ErrorInsToolType {
            get {
                return ResourceManager.GetString("ErrorInsToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de expiración.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumentos.
        /// </summary>
        public static string Instruments {
            get {
                return ResourceManager.GetString("Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos datos.
        /// </summary>
        public static string NewData {
            get {
                return ResourceManager.GetString("NewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo instrumento.
        /// </summary>
        public static string NewTool {
            get {
                return ResourceManager.GetString("NewTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo tipo de instrumentos.
        /// </summary>
        public static string NewToolType {
            get {
                return ResourceManager.GetString("NewToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros que mostrar.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No disponible.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir con Pintado.
        /// </summary>
        public static string RightArrow {
            get {
                return ResourceManager.GetString("RightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumento seleccionado.
        /// </summary>
        public static string SelectedTool {
            get {
                return ResourceManager.GetString("SelectedTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo de Tenaris.
        /// </summary>
        public static string TenarisLogo {
            get {
                return ResourceManager.GetString("TenarisLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de instrumentos.
        /// </summary>
        public static string ToolAssignation {
            get {
                return ResourceManager.GetString("ToolAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de herramientas.
        /// </summary>
        public static string ToolCatalog {
            get {
                return ResourceManager.GetString("ToolCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas.
        /// </summary>
        public static string ToolIndexPageTitle {
            get {
                return ResourceManager.GetString("ToolIndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de instrumentos.
        /// </summary>
        public static string ToolType {
            get {
                return ResourceManager.GetString("ToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de tipos de herramientas.
        /// </summary>
        public static string ToolTypeCatalog {
            get {
                return ResourceManager.GetString("ToolTypeCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de instrumentos.
        /// </summary>
        public static string ToolTypeIndexPageTitle {
            get {
                return ResourceManager.GetString("ToolTypeIndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar para control.
        /// </summary>
        public static string UpArrowControlImageAlt {
            get {
                return ResourceManager.GetString("UpArrowControlImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar para medición.
        /// </summary>
        public static string UpArrowMeasureImageAlt {
            get {
                return ResourceManager.GetString("UpArrowMeasureImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string UpdateImageAlt {
            get {
                return ResourceManager.GetString("UpdateImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de expiración no puede ser menor a la fecha de calibración.
        /// </summary>
        public static string ValidationExpirationDate {
            get {
                return ResourceManager.GetString("ValidationExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un instrumento de este tipo asociado a la máquina..
        /// </summary>
        public static string ValidationSameTypeAssignation {
            get {
                return ResourceManager.GetString("ValidationSameTypeAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código para el instrumento es obligatorio.
        /// </summary>
        public static string ValidationToolCodeMissing {
            get {
                return ResourceManager.GetString("ValidationToolCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código para el instrumento no debe de exceder 20 caracteres.
        /// </summary>
        public static string ValidationToolCodeTooLong {
            get {
                return ResourceManager.GetString("ValidationToolCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre para el tipo de instrumento es obligatorio..
        /// </summary>
        public static string ValidationToolTypeNameMissing {
            get {
                return ResourceManager.GetString("ValidationToolTypeNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre para el tipo de instrumento no debe de exceder 50 caracteres..
        /// </summary>
        public static string ValidationToolTypeNameTooLong {
            get {
                return ResourceManager.GetString("ValidationToolTypeNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe seleccionar un tipo de instrumento..
        /// </summary>
        public static string ValidationTypeMissing {
            get {
                return ResourceManager.GetString("ValidationTypeMissing", resourceCulture);
            }
        }
    }
}
